### ISSUE TITLE
Unable to create cost raster

### ISSUE THREAD

**Issue by NorthLand2** [lachlangrose/GeoTools#6]
Unable to create cost raster from input raster in the cost calculator tab. Get the following error.
1	Traceback (most recent call last):
			  File "C:/Users/PC/.qgis2/python/plugins\GeoTrace\geo_trace_dialog.py", line 330, in run_costcalculator
			    calc.run_calculator(c[0],self.cost_name.text())
			  File "C:/Users/PC/.qgis2/python/plugins\GeoTrace\gttracetool.py", line 475, in run_calculator
			    self.numpy_to_layer(array,name)
			  File "C:/Users/PC/.qgis2/python/plugins\GeoTrace\gttracetool.py", line 464, in numpy_to_layer
			    dsOut.SetGeoTransform(self.transform)
			AttributeError: 'NoneType' object has no attribute 'SetGeoTransform'

**Comment by lachlangrose** [comment]
Hi Northland2,

Could you please try using the bingie bingie data from https://figshare.com/articles/GeoTrace_and_Compass_rapid_trace-mapping_example_data_/5266603 

1. Try and create a darkness image using one of the ortho photos
2. Use one of the filters on the created darkness raster, you cannot calculate the filters on standard images because there are too many channels. 

If this works it is possible that there is an error with the coordinate system you are using for the raster. If you can share the raster then I could work out what the problem might be.

**Comment by NorthLand2** [comment]
I misunderstood the way the plugin works. I was trying to use non-optical data for processing.

**Comment by samthiele** [comment]
Glad you figured it out @NorthLand2. I'm unsure what you mean by non-optical data; the plugin should work for any single channel raster (e.g. topography, geophysics, grey-scale orthoimagery etc). 

Anyway - sounds like this is fixed so I'll close the issue. Please let us know if you have any more problems.

**Comment by NorthLand2** [comment]
Oh, if it's supposed to be able to create cost rasters from any single band raster, than the problem still exists. Projection was mentioned as a possible issue. Is a certain projection or datum required? or is geographic what's needed?

**Comment by lachlangrose** [comment]
Some custom coordinate systems can cause issues, we had some issues with some new zealand crs. Is it possible for you to share the data with us?

**Comment by Lautaro22** [comment]
Hi I have this problem:
\Users\lauta\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\GeoTrace\tools\gttracetool.py", line 492, in layer_to_numpy
              self.arrays.append(np.rot90(array,3))
             AttributeError: 'CostCalculator' object has no attribute 'arrays'
I did it with the darkness raster I got with the cost calculation option 
thank you for your answer
